name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  cd:
    name: Build Container Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ bar, foo ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e # v5.5.0
        id: meta
        with:
          images: |
            ghcr.io/${{ github.actor }}/monorepo-${{ matrix.service }}
          tags: |
            type=sha,enable=true,format=long,priority=200
            type=raw,enable=true,value=latest,priority=100

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
