name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: Build Container Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ bar, foo ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Docker meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.5.0
        id: meta
        with:
          images: |
            ghcr.io/tranngoclam/monorepo-${{ matrix.service }}
          tags: |
            type=sha,enable=true,format=long,priority=200
            type=raw,enable=true,value=latest,priority=100

      - name: Build/Tag/Push Docker Image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
