name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-bazel:
    name: Test (Bazel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazelisk test //... --test_output=errors

  test-go:
    name: Test (Go)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [api, bar, foo, lib]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go test -v ./...
        working-directory: ${{ matrix.dir }}
