name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-bazel:
    name: Test (Bazel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazelisk test //... --test_output=errors

  test-go:
    name: Test (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: foo/go.mod
          cache-dependency-path: foo/go.sum
          cache: true
      - run: |
          go test -v foo/...
